swagger: "2.0"
info:
  description: "これはペットストアに関するAPIです。"
  version: "1.0.0"
  title: "Petstore API"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
produces:
  - "application/json"
consumes:
  - application/x-www-form-urlencoded
paths:
  /api/pets/{petId}:
    get:
      summary: "ペット情報API"
      description: "指定されたpetIdの情報を返します"
      operationId: 'get_pet_by_id'
      tags:
      - 'pet'
      parameters:
      - name: "petId"
        in: "path"
        description: "取得したいペットのID"
        required: true
        type: "integer"
      responses:
        200:
          description: "成功時のレスポンス"
          schema:
            $ref: '#/definitions/Pet'

definitions:
  Pet:
    type: object
    required:
     - id
     - name
    properties:
      id:
        type: "integer"
      name:
        type: "string"
        example: "doggie"
